const icons = {
    menu: require('../assets/images/icons/icon_menu.png'),
    add_black: require('../assets/images/icons/icon_add_preta.png'),
    add_white: require('../assets/images/icons/icon_add_branca.png'),
    menos_black: require('../assets/images/icons/icon_menos_preta.png'),
    menos_white: require('../assets/images/icons/icon_menos_branca.png'),
    woman_black: require('../assets/images/icons/woman_icon.png'),
    man_black: require('../assets/images/icons/man_icon.png'),
    kid_black: require('../assets/images/icons/kid_icon.png'),
    add_woman_white: require('../assets/images/icons/icon_addHomem_branca.png'),
    add_man_white: require('../assets/images/icons/icon_addHomem_branca.png'),
    add_kid_white: require('../assets/images/icons/icon_crianca_branca.png'),
    cerveja_white: require('../assets/images/icons/icon_cerveja_branca.png'),
    cerveja_black: require('../assets/images/icons/icon_cerveja_preta.png'),
    people_white: require('../assets/images/icons/icon_pessoas_branca.png'),
    boi_black: require('../assets/images/icons/icon_boi_preta.png'),
    boi_white: require('../assets/images/icons/icon_boi_branca.png'),
    porco_black: require('../assets/images/icons/icon_porco_preta.png'),
    porco_white: require('../assets/images/icons/icon_porco_white.png'),
    frango_white: require('../assets/images/icons/icon_galinha_branca.png'),
    frango_black: require('../assets/images/icons/icon_galinha_preta.png'),
    corte_bovino: require('../assets/images/icons/icon_cortebovino_branca.png'),
    corte_suino: require('../assets/images/icons/icon_suino_porco.png'),
    refri_white: require('../assets/images/icons/icon_refri_branca.png'),
    refri_black: require('../assets/images/icons/icon_refri_preta.png'),
    suco_black: require('../assets/images/icons/icon_suco_preta.png'),
    suco_white: require('../assets/images/icons/icon_suco_branca.png'),
    agua_white: require('../assets/images/icons/icon_watter_branca.png'),
    agua_black: require('../assets/images/icons/icon_watter_preta.png'),
    math_white: require('../assets/images/icons/icon_math_branca.png'),
    churras_white: require('../assets/images/icons/icon_churras_branca.png'),
    receita_white: require('../assets/images/icons/icon_receita_branca.png'),
    next: require('../assets/images/icons/icon_next.png'),
    next_white: require('../assets/images/icons/icon_next_white.png'),
    arrow_back_black: require('../assets/images/icons/icon_back_black.png'),
    arrow_back_white: require('../assets/images/icons/icon_back_white.png'),
}

export default icons;